FROM node:16-alpine AS build

WORKDIR /app

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

COPY package*.json ./

RUN npm install --production && \
    npm cache clean --force

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

COPY --from=build /wait /wait
RUN chmod +x /wait

EXPOSE 80

CMD ["sh", "-c", "/wait && nginx -g 'daemon off;'"]
