version: '3.8'

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper

  python-backend:
    build: ./backend/python-rag-app
    container_name: python-backend
    ports:
      - "8000:8000"
    environment:
      KAFKA_BROKER: kafka:9092
      DATABASE_URL: postgresql+psycopg2://postgres:1234@postgres:5432/rag_db
      HUGGINGFACEHUB_API_TOKEN:  # enter your hugginface key her
      KAFKA_INGEST_TOPIC: ingestion-trigger
      KAFKA_COMPLETED_TOPIC: ingestion-completed
    depends_on:
      - kafka
      - zookeeper
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  nestjs-backend:
    build: ./backend/nest-auth-app
    container_name: nestjs-backend
    ports:
      - "3001:3001"
    environment:
      KAFKA_INGEST_TOPIC: ingestion-trigger
      KAFKA_COMPLETED_TOPIC: ingestion-completed
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      DB_DATABASE: rag_db
      KAFKA_BROKER: kafka:9092
      APP_SECRET: 0dd8d1d7c673300e0e800e10e13eb6ee1414c140e046ebf7e2229010ab7ab79a10f06fddeebabfb428b6a380aa12654c
    depends_on:
      - kafka
      - zookeeper
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  react-frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - nestjs-backend
      - python-backend

  postgres:
    image: ankane/pgvector:latest 
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rag_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  kafka_data:
  zookeeper_data:
  postgres_data: